# docker-compose.yml
version: "3"
services:
  app:
    image: sharadregoti/telegram:0.1.0
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword